//用户信息
export const USERINFO_UPDATE = 'USERINFO_UPDATE'

// 广告信息
export const ADINFO_UPDATE = 'ADINFO_UPDATE'

// 推荐信息
export const RECOMMENDINFO_UPDATE = 'RECOMMENDINFO_UPDATE'

// 增加推荐信息
export const RECOMMENDINFO_ADD = 'RECOMMENDINFO_ADD'